// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuff.proto

public final class Protobuff {
  private Protobuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VendorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string vendorName = 1;
    /**
     * <code>optional string vendorName = 1;</code>
     */
    boolean hasVendorName();
    /**
     * <code>optional string vendorName = 1;</code>
     */
    String getVendorName();
    /**
     * <code>optional string vendorName = 1;</code>
     */
    com.google.protobuf.ByteString
        getVendorNameBytes();

    // optional string paidDate = 2;
    /**
     * <code>optional string paidDate = 2;</code>
     */
    boolean hasPaidDate();
    /**
     * <code>optional string paidDate = 2;</code>
     */
    String getPaidDate();
    /**
     * <code>optional string paidDate = 2;</code>
     */
    com.google.protobuf.ByteString
        getPaidDateBytes();

    // optional string vendorType = 3;
    /**
     * <code>optional string vendorType = 3;</code>
     */
    boolean hasVendorType();
    /**
     * <code>optional string vendorType = 3;</code>
     */
    String getVendorType();
    /**
     * <code>optional string vendorType = 3;</code>
     */
    com.google.protobuf.ByteString
        getVendorTypeBytes();

    // optional float paidAmount = 4;
    /**
     * <code>optional float paidAmount = 4;</code>
     */
    boolean hasPaidAmount();
    /**
     * <code>optional float paidAmount = 4;</code>
     */
    float getPaidAmount();
  }
  /**
   * Protobuf type {@code Vendor}
   */
  public static final class Vendor extends
      com.google.protobuf.GeneratedMessage
      implements VendorOrBuilder {
    // Use Vendor.newBuilder() to construct.
    private Vendor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Vendor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Vendor defaultInstance;
    public static Vendor getDefaultInstance() {
      return defaultInstance;
    }

    public Vendor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Vendor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              vendorName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              paidDate_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              vendorType_ = input.readBytes();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              paidAmount_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuff.internal_static_Vendor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuff.internal_static_Vendor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuff.Vendor.class, Protobuff.Vendor.Builder.class);
    }

    public static com.google.protobuf.Parser<Vendor> PARSER =
        new com.google.protobuf.AbstractParser<Vendor>() {
      public Vendor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vendor(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Vendor> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string vendorName = 1;
    public static final int VENDORNAME_FIELD_NUMBER = 1;
    private Object vendorName_;
    /**
     * <code>optional string vendorName = 1;</code>
     */
    public boolean hasVendorName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string vendorName = 1;</code>
     */
    public String getVendorName() {
      Object ref = vendorName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vendorName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string vendorName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVendorNameBytes() {
      Object ref = vendorName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        vendorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string paidDate = 2;
    public static final int PAIDDATE_FIELD_NUMBER = 2;
    private Object paidDate_;
    /**
     * <code>optional string paidDate = 2;</code>
     */
    public boolean hasPaidDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string paidDate = 2;</code>
     */
    public String getPaidDate() {
      Object ref = paidDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          paidDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string paidDate = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPaidDateBytes() {
      Object ref = paidDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        paidDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string vendorType = 3;
    public static final int VENDORTYPE_FIELD_NUMBER = 3;
    private Object vendorType_;
    /**
     * <code>optional string vendorType = 3;</code>
     */
    public boolean hasVendorType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string vendorType = 3;</code>
     */
    public String getVendorType() {
      Object ref = vendorType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vendorType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string vendorType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVendorTypeBytes() {
      Object ref = vendorType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        vendorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional float paidAmount = 4;
    public static final int PAIDAMOUNT_FIELD_NUMBER = 4;
    private float paidAmount_;
    /**
     * <code>optional float paidAmount = 4;</code>
     */
    public boolean hasPaidAmount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float paidAmount = 4;</code>
     */
    public float getPaidAmount() {
      return paidAmount_;
    }

    private void initFields() {
      vendorName_ = "";
      paidDate_ = "";
      vendorType_ = "";
      paidAmount_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVendorNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPaidDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getVendorTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, paidAmount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVendorNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPaidDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getVendorTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, paidAmount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Protobuff.Vendor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuff.Vendor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuff.Vendor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuff.Vendor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuff.Vendor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuff.Vendor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Protobuff.Vendor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Protobuff.Vendor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Protobuff.Vendor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuff.Vendor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Protobuff.Vendor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Vendor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Protobuff.VendorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protobuff.internal_static_Vendor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protobuff.internal_static_Vendor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protobuff.Vendor.class, Protobuff.Vendor.Builder.class);
      }

      // Construct using Protobuff.Vendor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        vendorName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        paidDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        vendorType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        paidAmount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protobuff.internal_static_Vendor_descriptor;
      }

      public Protobuff.Vendor getDefaultInstanceForType() {
        return Protobuff.Vendor.getDefaultInstance();
      }

      public Protobuff.Vendor build() {
        Protobuff.Vendor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Protobuff.Vendor buildPartial() {
        Protobuff.Vendor result = new Protobuff.Vendor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.vendorName_ = vendorName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.paidDate_ = paidDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.vendorType_ = vendorType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.paidAmount_ = paidAmount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protobuff.Vendor) {
          return mergeFrom((Protobuff.Vendor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protobuff.Vendor other) {
        if (other == Protobuff.Vendor.getDefaultInstance()) return this;
        if (other.hasVendorName()) {
          bitField0_ |= 0x00000001;
          vendorName_ = other.vendorName_;
          onChanged();
        }
        if (other.hasPaidDate()) {
          bitField0_ |= 0x00000002;
          paidDate_ = other.paidDate_;
          onChanged();
        }
        if (other.hasVendorType()) {
          bitField0_ |= 0x00000004;
          vendorType_ = other.vendorType_;
          onChanged();
        }
        if (other.hasPaidAmount()) {
          setPaidAmount(other.getPaidAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protobuff.Vendor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protobuff.Vendor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string vendorName = 1;
      private Object vendorName_ = "";
      /**
       * <code>optional string vendorName = 1;</code>
       */
      public boolean hasVendorName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string vendorName = 1;</code>
       */
      public String getVendorName() {
        Object ref = vendorName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          vendorName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string vendorName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVendorNameBytes() {
        Object ref = vendorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          vendorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string vendorName = 1;</code>
       */
      public Builder setVendorName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        vendorName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string vendorName = 1;</code>
       */
      public Builder clearVendorName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        vendorName_ = getDefaultInstance().getVendorName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string vendorName = 1;</code>
       */
      public Builder setVendorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        vendorName_ = value;
        onChanged();
        return this;
      }

      // optional string paidDate = 2;
      private Object paidDate_ = "";
      /**
       * <code>optional string paidDate = 2;</code>
       */
      public boolean hasPaidDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string paidDate = 2;</code>
       */
      public String getPaidDate() {
        Object ref = paidDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          paidDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string paidDate = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPaidDateBytes() {
        Object ref = paidDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          paidDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string paidDate = 2;</code>
       */
      public Builder setPaidDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        paidDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string paidDate = 2;</code>
       */
      public Builder clearPaidDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        paidDate_ = getDefaultInstance().getPaidDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string paidDate = 2;</code>
       */
      public Builder setPaidDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        paidDate_ = value;
        onChanged();
        return this;
      }

      // optional string vendorType = 3;
      private Object vendorType_ = "";
      /**
       * <code>optional string vendorType = 3;</code>
       */
      public boolean hasVendorType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string vendorType = 3;</code>
       */
      public String getVendorType() {
        Object ref = vendorType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          vendorType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string vendorType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVendorTypeBytes() {
        Object ref = vendorType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          vendorType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string vendorType = 3;</code>
       */
      public Builder setVendorType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        vendorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string vendorType = 3;</code>
       */
      public Builder clearVendorType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        vendorType_ = getDefaultInstance().getVendorType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string vendorType = 3;</code>
       */
      public Builder setVendorTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        vendorType_ = value;
        onChanged();
        return this;
      }

      // optional float paidAmount = 4;
      private float paidAmount_ ;
      /**
       * <code>optional float paidAmount = 4;</code>
       */
      public boolean hasPaidAmount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float paidAmount = 4;</code>
       */
      public float getPaidAmount() {
        return paidAmount_;
      }
      /**
       * <code>optional float paidAmount = 4;</code>
       */
      public Builder setPaidAmount(float value) {
        bitField0_ |= 0x00000008;
        paidAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float paidAmount = 4;</code>
       */
      public Builder clearPaidAmount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        paidAmount_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Vendor)
    }

    static {
      defaultInstance = new Vendor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Vendor)
  }

  public interface VendorListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Vendor list = 1;
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    java.util.List<Vendor>
        getListList();
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    Protobuff.Vendor getList(int index);
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    java.util.List<? extends VendorOrBuilder>
        getListOrBuilderList();
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    Protobuff.VendorOrBuilder getListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code VendorList}
   */
  public static final class VendorList extends
      com.google.protobuf.GeneratedMessage
      implements VendorListOrBuilder {
    // Use VendorList.newBuilder() to construct.
    private VendorList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VendorList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VendorList defaultInstance;
    public static VendorList getDefaultInstance() {
      return defaultInstance;
    }

    public VendorList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VendorList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<Vendor>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readMessage(Protobuff.Vendor.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuff.internal_static_VendorList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuff.internal_static_VendorList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuff.VendorList.class, Protobuff.VendorList.Builder.class);
    }

    public static com.google.protobuf.Parser<VendorList> PARSER =
        new com.google.protobuf.AbstractParser<VendorList>() {
      public VendorList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VendorList(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<VendorList> getParserForType() {
      return PARSER;
    }

    // repeated .Vendor list = 1;
    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<Vendor> list_;
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    public java.util.List<Vendor> getListList() {
      return list_;
    }
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    public java.util.List<? extends VendorOrBuilder>
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    public Protobuff.Vendor getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .Vendor list = 1;</code>
     */
    public Protobuff.VendorOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Protobuff.VendorList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuff.VendorList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuff.VendorList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protobuff.VendorList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protobuff.VendorList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuff.VendorList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Protobuff.VendorList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Protobuff.VendorList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Protobuff.VendorList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Protobuff.VendorList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Protobuff.VendorList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VendorList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Protobuff.VendorListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protobuff.internal_static_VendorList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protobuff.internal_static_VendorList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protobuff.VendorList.class, Protobuff.VendorList.Builder.class);
      }

      // Construct using Protobuff.VendorList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protobuff.internal_static_VendorList_descriptor;
      }

      public Protobuff.VendorList getDefaultInstanceForType() {
        return Protobuff.VendorList.getDefaultInstance();
      }

      public Protobuff.VendorList build() {
        Protobuff.VendorList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Protobuff.VendorList buildPartial() {
        Protobuff.VendorList result = new Protobuff.VendorList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protobuff.VendorList) {
          return mergeFrom((Protobuff.VendorList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protobuff.VendorList other) {
        if (other == Protobuff.VendorList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protobuff.VendorList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protobuff.VendorList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Vendor list = 1;
      private java.util.List<Vendor> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<Vendor>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Protobuff.Vendor, Protobuff.Vendor.Builder, Protobuff.VendorOrBuilder> listBuilder_;

      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public java.util.List<Vendor> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Protobuff.Vendor getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Builder setList(
          int index, Protobuff.Vendor value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Builder setList(
          int index, Protobuff.Vendor.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Builder addList(Protobuff.Vendor value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Builder addList(
          int index, Protobuff.Vendor value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Builder addList(
          Protobuff.Vendor.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Builder addList(
          int index, Protobuff.Vendor.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Builder addAllList(
          Iterable<? extends Vendor> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          super.addAll(values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Protobuff.Vendor.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Protobuff.VendorOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public java.util.List<? extends VendorOrBuilder>
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Protobuff.Vendor.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            Protobuff.Vendor.getDefaultInstance());
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public Protobuff.Vendor.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, Protobuff.Vendor.getDefaultInstance());
      }
      /**
       * <code>repeated .Vendor list = 1;</code>
       */
      public java.util.List<Vendor.Builder>
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Protobuff.Vendor, Protobuff.Vendor.Builder, Protobuff.VendorOrBuilder>
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Protobuff.Vendor, Protobuff.Vendor.Builder, Protobuff.VendorOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:VendorList)
    }

    static {
      defaultInstance = new VendorList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VendorList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Vendor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Vendor_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VendorList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VendorList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017protobuff.proto\"V\n\006Vendor\022\022\n\nvendorNam" +
      "e\030\001 \001(\t\022\020\n\010paidDate\030\002 \001(\t\022\022\n\nvendorType\030" +
      "\003 \001(\t\022\022\n\npaidAmount\030\004 \001(\002\"#\n\nVendorList\022" +
      "\025\n\004list\030\001 \003(\0132\007.Vendor"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Vendor_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Vendor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Vendor_descriptor,
              new String[] { "VendorName", "PaidDate", "VendorType", "PaidAmount", });
          internal_static_VendorList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_VendorList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_VendorList_descriptor,
              new String[] { "List", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
